### ISSUE TITLE
Release 9.4 not yet available

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/pymdown-extensions-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

pymdown-extensions 9.4 has been available from pypi for over a month, but still has not
appeared in conda-forge, so presumably there is something wrong with the feedstock....

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by dhirschfeld** [comment]
Should be available in an hour or two...
